[build]
  command = "hugo --gc --minify && npx pagefind --source 'public'"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.136.5"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture && npx pagefind --source 'public'"

[context.branch-deploy]
  command = "hugo --gc --minify && npx pagefind --source 'public'"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true
